services:
  - type: web
    name: qgoptimus-backend
    runtime: docker
    dockerfilePath: ./Dockerfile
    dockerContext: .
    plan: free
    healthCheckPath: /
    envVars:
      - key: PORT
        value: 8000
